name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:12.14.1-alpine3.10
        with: 
          entrypoint: /bin/echo
          args: Hello World
      - name: log node version with docker container in steps
        uses: docker://node:12.14.1-alpine3.10
        with: 
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v3.0.2
      - name: Run a script
        uses: docker://node:12.14.1-alpine3.10
        with: 
          entrypoint: ./script.sh
          args: "Some String"
  node-docker:
    runs-on: ubuntu-latest
    services: 
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Post a user
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username\": \"hello\",\"address\": \"dwded\"}'"
      - name: Get Users
        run: "curl  http://localhost:3001/api/users"